### ISSUE TITLE
Climber Code

### ISSUE THREAD

**Issue by gldeA** [Brown-County-FIRST-Robotics/1716-2024-robot#14]
The climber will eventually need code, but it's not designed yet.

**Comment by cfinn68916** [comment]
- [ ] Add control for 2 sparkmaxs
- [ ] PID based balancing by changing goal position based on gyro roll

**Comment by LucasLubinski** [comment]
Climber will contain 4 sensors. Each sensor has two points to read the magnet passing. The first should inform the arm to slow down, second should tell the arm to stop since its at the maximum distance.

[Sensor Datasheet](https://www.datasheets.com/part-details/mrs--087-b-12-bimba-ltd-46375354#datasheet)
